### ISSUE TITLE
Syntax decorations override theme preferences

### ISSUE THREAD

**Issue by mgmeyers** [svsool/memo#133]
Since the colors for syntax decoration (wiki-link) colors are hardcoded here: https://github.com/svsool/vscode-memo/blob/master/src/features/syntaxDecorations.ts#L24-L33 there's no way to have them respect the current theme.

I would love it if I could disable these syntax decorations or if they were exposed as themeable tokens, rather than hard-coded. The latter is how `vscode-markdown-notes` handles wiki-link styling: 

https://github.com/kortina/vscode-markdown-notes/blob/master/syntaxes/notes.tmLanguage.json
https://github.com/kortina/vscode-markdown-notes/blob/master/language-configuration.json
https://github.com/kortina/vscode-markdown-notes/blob/master/package.json#L28-L45

**Comment by svsool** [comment]
> I would love it if I could disable these syntax decorations or if they were exposed as themeable tokens, rather than hard-coded. The latter is how vscode-markdown-notes handles wiki-link styling:

Memo does not use language contribution and tokens because it has more complex logic for handling wikilinks decorations in certain contexts, for instance, Memo does not highlight links within fenced code blocks (as well as code spans) on purpose, but vscode-markdown-notes does. However, I don't disagree that having a possibility to style it is a good option.

**Comment by mgmeyers** [comment]
Ah, I see, that makes a lot of sense!

**Comment by mgmeyers** [comment]
Poked around to see what could be done here. It looks like we could define the colors in `package.json`:

```
"contributes": {
  "colors": [{
      "id": "some-id",
      "description": "Some description",
      "defaults": {
          "dark": "#112233",
          "light": "#ddeeff",
          "highContrast": "foreground"
      }
  }]
}
```

Then access the colors like so:

```
new vscode.ThemeColor('some-id')
```

Should should be overridable via themes and workspace color settings.

(source: https://github.com/microsoft/vscode/issues/32813#issuecomment-414227205)

**Comment by svsool** [comment]
Thanks for your time and for looking into this problem!

Using `ThemeColor` sounds good to me, and we can try that. Do you find this PR useful https://github.com/svsool/vscode-memo/pull/134 if colors are configurable?

**Comment by mgmeyers** [comment]
Yeah, I'd still prefer to defer to whatever theme I'm using, but at the same time, it wouldn't be too big of a deal to me to define some colors if I had to go about it that way.

I stumbled across this yesterday: [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) also takes the approach of #134 by defining a `markdown.extension.syntax.decorations` boolean: https://github.com/yzhang-gh/vscode-markdown/blob/master/package.json#L324-L328

**Comment by svsool** [comment]
after this feature https://github.com/svsool/memo/issues/560 parent theme colors should be inherited
