### ISSUE TITLE
Feature request: Add ".msg" (Outlook e-mail messages) to the list of supported other file extensions

### ISSUE THREAD

**Issue by cthomp-jus** [svsool/memo#470]
Would it be possible to add ".msg" to the list of supported file extensions? (otherExts in utils.ts) I often save Outlook e-mail messages to various folders and would like to refer to them in my notes.

This is probably most useful for Windows users. I think it makes sense because the other Microsoft Office filetypes are already supported (.doc, .xls, etc.).

Thanks for a great extension!

**Comment by svsool** [comment]
Probably it would be more scalable to allow people define their own extensions to index via VSCode settings.

Currently extensions defined [here](https://github.com/svsool/vscode-memo/blob/master/src/utils/utils.ts#L18) and example of settings can be found in [package.json](https://github.com/svsool/vscode-memo/blob/master/package.json#L86-L140).

I think it could be a good first issue to contribute for someone.
