### ISSUE TITLE
Request for export of wiki links data

### ISSUE THREAD

**Issue by victorkane** [svsool/memo#473]
Hi there, thanks so much for Memo! I use it every day and love the wiki links and the preview feature, and wouldn't want to use any other system, so happy I have all these features in VS Code.

One feature I am missing is the ability to export a folder to "standard" markdown so that I can put it into a publishing system, with the links working.

Where is the data on links stored on my computer? I would like to access it to see if I can translate the links myself for, say, a single file or small group of files, and share that back with those using Memo.

Thanks in advance for your assistance!

**Comment by srid** [comment]
> One feature I am missing is the ability to export a folder to "standard" markdown so that I can put it into a publishing system, with the links working.

Note, you can *also* achieve this without doing any export. Both [neuron](https://neuron.zettel.page/) and the subsequent [Emanote](https://note.ema.srid.ca/) support *direct* publishing of Markdown/wiki-link based Zettelkasten notebooks.

[My entire website](https://www.srid.ca/), for example, is published this way. You can see that it is just [a bunch of Markdown files](https://github.com/srid/www.srid.ca) linked using `[[..]]` wiki-links (not "standard" Markdown links).

**Comment by victorkane** [comment]
Thanks for your suggestion, @srid 

The problem is I was using he short name option for links (now I'm using the long name, which includes the complete relative path), so an external app would have no way of knowing the path of the target being linked. Or am I missing something?

**Comment by srid** [comment]
It depends on the tool. Emanote recognizes wiki-links even with paths like `[[Foo/Bar]]` but not yet those with ".." in it. See https://github.com/srid/emanote/discussions/115

**Comment by victorkane** [comment]
@srid emanote looks cool, will check it out! Thanks for your suggestions. That's the kind of setup I need. Would still like to see how I can locate access to the data on links stored by Memo, though.

**Comment by srid** [comment]
What do you mean by "data on links" exactly? Emanote does not store any special data; it directly reads and operates on Markdown file. 

Neuron too does that same, but it has a command `neuron query` which will export the graph (with note metadata as vertex, and note links as edges) as JSON (Emanote should hopefully get the same feature soon).

**Comment by svsool** [comment]
hi, I assume that this [cli tool](https://github.com/zoni/obsidian-export) should work for your case, let me know, thanks!
