### ISSUE TITLE
.gitignore is not respected

### ISSUE THREAD

**Issue by srid** [svsool/memo#539]
I have `.direnv` listed in the project's `.gitignore` file, yet this extension looks for .md files in `./.direnv` -- and there are plenty of them (marked as read-only), given that I use Nix. 

`.direnv` refers to build artifacts, and ought not to be traversed. Is there a way to tell vscode-memo to ignore specific folders?

**Comment by svsool** [comment]
Does following setting help if you add a new pattern?

![image](https://user-images.githubusercontent.com/1452141/156842065-a258e609-24b5-4084-afdb-6581f8bd464b.png)

I'd expect `.gitignore` to be respected automatically by vscode on search per following though:

![image](https://user-images.githubusercontent.com/1452141/156842194-5a15cc00-947c-4933-bee1-54837f0554d7.png)

**Comment by srid** [comment]
Ah, yes, `Search: Exclude` setting works for me. 

`search.useIgnoreFiles` is already on; so I don't know why it didn't work before.

**Comment by svsool** [comment]
I checked vscode's api implementation and .gitignore is not respected OOTB, please use `Search: Exclude` or `File: Exclude` instead.
