### ISSUE TITLE
Use syntax injection for wikilink highlighting

### ISSUE THREAD

**Issue by memeplex** [svsool/memo#560]
As described in https://github.com/svsool/vscode-memo/pull/479#issuecomment-1116866586:

> - Simpler declarative implementation (I think you can get rid of the entire syntaxDecorations.ts file)
> - Better performance
> - No flickering and weird intermediate colorization (see screenshot below)
> - Customizable color (using standard token highlighting settings)
> - Color appropriately changes with theme (sensible default that uses base link color)

<img width="47" alt="image" src="https://user-images.githubusercontent.com/2845433/166618769-575eec49-fece-4c8e-ac10-19e1330023e7.png">

**Comment by memeplex** [comment]
You might be interested in https://github.com/primer/github-vscode-theme/issues/320. I noticed that syntax injected wikilinks are not released yet and that wikilinks decorations are conflicting with such a popular theme may be a reason to push those changes.

**Comment by svsool** [comment]
It should be released now.
