### ISSUE TITLE
$CURRENT_SECONDS_UNIX in Link Rule Variables is incorrectly evaluated

### ISSUE THREAD

**Issue by kevinjalbert** [svsool/memo#570]
`$CURRENT_SECONDS_UNIX - The number of seconds since the Unix epoch`

This seems to 'trigger' `$CURRENT_SECOND`, then add the `S_UNIX` on.

For example: `$CURRENT_SECONDS_UNIX` produces `38X_UNIX`.

**Comment by svsool** [comment]
thanks for reporting, fix will be released in the next version.
