### ISSUE TITLE
markdown.experimental.updateLinksOnFileMove.enabled

### ISSUE THREAD

**Issue by mrienstra** [svsool/memo#598]
The `markdown.experimental.updateLinksOnFileMove.enabled` setting was released in the [August 2022 version (1.71) of Visual Studio Code](https://code.visualstudio.com/updates/v1_71#_markdown-link-update-on-file-move-and-rename).

>With this new experimental setting enabled, VS Code will automatically update links and images in Markdown when files are moved or renamed in the VS Code Explorer:
>
>This new behavior can be enabled using the `markdown.experimental.updateLinksOnFileMove`.enabled setting. You can control the types of files affected using `markdown.experimental.updateLinksOnFileMove.externalFileGlobs`.

I haven't tested it yet, but I can imagine this new setting might already clash with Memo's [`links.sync.enabled`](https://github.com/svsool/memo/search?q=links.sync.enabled), though I'd imagine very few people will be affected if so.

Still, it seems wise to keep an eye on `updateLinksOnFileMove`, in the near future it may no longer be "experimental" (though I have no idea how long that process generally takes).

When (if) it becomes a full-fledged setting, some possibilities:

1. Inform users that they shouldn't enable it, if it clashes with Memo.
2. Detect when it is enabled (alongside Memo's `links.sync.enabled`), and:
  A) Warn the user and / or
  B) Disable `links.sync.enabled`
3. Alter Memo to rely on VS Code's `updateLinksOnFileMove` -- maybe it'll be a better implementation in some way, and doing so would simplify Memo, meaning fewer possible sources of bugs / devs can focus efforts on other features.

**Comment by svsool** [comment]
Thanks for notifying about it. Have you tested whether it's a problem or not? I'd guess that it shouldn't conflict with Memo, because native markdown links are different to wiki-links.

**Comment by aksarben** [comment]
I’m unfamiliar with “Memo,” but the setting doesn’t work for me at all ("markdown.experimental.updateLinksOnFileMove.enabled": "always" ). Example of link that is  not updated:

**`<a href="../../../../../htm/a/l/l/h/allhahod.htm">All Hail, Ho­ly Day!</a>`**

If I rename or move a file, hrefs pointing to it remain unchanged, resulting in broken links. VSC does not display an error message or other problem indicator.

My system info:

**Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No**

**Comment by svsool** [comment]
This is a wrong issue and repo to report about this problem.

Please report it to the upstream ([vscode](https://github.com/microsoft/vscode) in this case).

Try also `[All Hail, Ho­ly Day!](../../../../../htm/a/l/l/h/allhahod.htm)` instead. 

That's how it was demoed [here](https://code.visualstudio.com/updates/v1_71#_preview-features).

**Comment by mrienstra** [comment]
@svsool re: orthogonal as it does not affect wikilinks: good call. I opened a few similar issues on similar projects (Foam, Dendron), with the thought that this new VS Code feature might in some way interact. I'll close this issue. Thanks for responding!
