### ISSUE TITLE
Daily notes don't automatically create in a Journal or Daily Notes folder

### ISSUE THREAD

**Issue by b-cooney** [svsool/memo#601]
I was expecting to have something like `"memo.openDailyNote.directory"` available where I could set where I want Daily Notes to go (btw this would be good to have with all types of notes too) but it doesns't exist. Instead, these create in the workspace_root and I need to drag it into the Journal folder manually each time.

Is there another way to have Daily Notes create in the correct folder?

Thanks a lot!

**Comment by svsool** [comment]
Hi, this was already answered in this [issue](https://github.com/svsool/memo/issues/482), please check it out.
