### ISSUE TITLE
Feature Request: Checklist / Todo / Tasks

### ISSUE THREAD

**Issue by merqrial** [svsool/memo#625]
One amazing feature of obsidian is using the checkboxes and then using tasks or dataview or checklists etc, collate them in one view.
Is there any plan to have a better collating support for todo items across all the MD files in the workspace?

I looked at, https://github.com/usernamehw/vscode-todo-md. 
However, it wants you to keep all tasks in single file and can't be inside markdown files across the workspace.

Do you see any other tool that can be helpful if this is out of scope for memo?

**Comment by Semphora** [comment]
Have you seen https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree ? Markdown support and aggregation from multiple files.

**Comment by ez4gis** [comment]
+1 for "todo-tree". I'm a long-time happy user of the extension.
